# Generated by Django 4.1.6 on 2023-02-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_bed'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('doctor', models.CharField(max_length=50)),
                ('date', models.IntegerField()),
            ],
        ),
    ]
